### PR TITLE
document anyio.lowlevel.current_token

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by agronholm** [comment]
What is the benefit of documenting this, on its own? Sometimes I wish you wrote descriptions in your PRs.

**Comment by graingert** [comment]
> What is the benefit of documenting this, on its own? Sometimes I wish you wrote descriptions in your PRs.

It's part of the public API, it should be documented?

**Comment by agronholm** [comment]
By definition, if it's not documented, it's not part of the public API.

**Comment by graingert** [comment]
closed in favour of https://github.com/agronholm/anyio/pull/336

**Pull request closed without merging**
