### PR TITLE
add `wrapped` property to `Path`

### PR DESCRIPTION
**Pull request by valq7711**

### CODE REVIEW

**Comment by agronholm** [comment]
Why is `pathlib.Path(anyio_path)` not enough?

**Comment by valq7711** [comment]
> Why is `pathlib.Path(anyio_path)` not enough?

 it requires to import `pathlib.Path`

**Comment by agronholm** [comment]
So?

**Comment by valq7711** [comment]
It is redundant code (importing) and an extra `pathlib.Path` instance created every time we need a sync path

**Comment by agronholm** [comment]
I'd like to know more about your use case. This hasn't come up before.

**Comment by valq7711** [comment]
```python
class MockData:
    mock_data_json = anyio.Path('/mock_data/data.json')
    mock_data_json.parent.wrapped.mkdir(exist_ok=True)
```

**Comment by agronholm** [comment]
Doesn't seem like you need this for performance, just to save you a little bit of typing? I'll think this over.

**Comment by valq7711** [comment]
There is `wrapped` property for async file, why not to have the same for async path?

**Comment by valq7711** [comment]
There are sync-libraries (e.g. csv) that work with sync path and usually you need to do some async path checking (like a `.is_file()`) and then pass sync-path to these libraries `to_thread.run_sync()`, so I think it is a fairly common case when it needs to get sync-path from async-path.

**Comment by agronholm** [comment]
Do these APIs work solely with `Path`, or do they accept `os.PathLike`, like virtually all stdlib functions dealing with paths do?

**Comment by agronholm** [comment]
In the case of `AsyncFile`, it's stateful so you can't just convert it into a sync file descriptor without repercussions. That's why it has the `wrapped` property. Another reason for not having a `wrapped` property on the async `Path` is that, as alluded above, most APIs that take paths take any path-like objects, so an explicit conversion tends not be necessary anyway.

**Comment by agronholm** [comment]
Closing due to stalled discussion and a negative consensus on Gitter regarding this.

**Pull request closed without merging**
