### PR TITLE
Remove usage of socket.SocketType

### PR DESCRIPTION
**Pull request by JelleZijlstra**
SocketType is an alias for the private `_socket.socket` class, a superclass of `socket.socket`. It is better to just always use `socket.socket` in types. See https://bugs.python.org/issue44261 and python/typeshed#5545 for some context.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Looks like this exposes a few new mypy complaints. I will fix those.

**Comment by JelleZijlstra** [comment]
This should be good now. I checked both the current release of mypy and mypy+typeshed master.

A few tests in `test_to_process.py` fail for me locally on 3.7 (but not 3.8 or 3.9), but that seems unrelated to the changes in the PR.

**Comment by agronholm** [comment]
This still fails the linter tests. I suggest that you run `tox -p` locally first.

**Comment by JelleZijlstra** [comment]
Oops, sorry for missing that. Looks like I was on an old version of tox, because it passed for me locally.

**Review by agronholm — APPROVED** [review]

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
