### PR TITLE
Fix shield future to prevent erroneous RuntimeError

### LINKED ISSUE #706: Raising an error inside a task of a task group can produce: `RuntimeError: called 'started' twice on the same task status`
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.3.0

### Python version

3.12.2

### What happened?

Calling task_status.started() can raise `RuntimeError: called 'started' twice on the same task status` under certain circumstances (see examples), even though it was not called twice.
The reason for this is that the underlying future gets awaited in the start() method. When the start() method gets canceled, the underlying future gets also canceled which makes calling set_result on the future later fail and raise the erroneous RuntimeError.
This can be fixed by using asyncio.shield when awaiting the future.
https://github.com/agronholm/anyio/blob/05a3d02ed383f996ad93e8a7a4f6dcce153a06b6/src/anyio/_backends/_asyncio.py#L782

### How can we reproduce the bug?

```python
from anyio import create_task_group, run
from anyio.abc import TaskStatus


async def taskfunc(*, task_status: TaskStatus):
    task_status.started()
    raise ValueError


async def main():
    async with create_task_group() as tg:
        await tg.start(taskfunc)
        await tg.start(taskfunc)


run(main)
```
or
```python
from anyio import create_task_group, run
from anyio.abc import TaskStatus


async def taskfunc(*, task_status: TaskStatus):
    task_status.started()


async def main():
    async with create_task_group() as tg:
        coro = tg.start(taskfunc)
        tg.cancel_scope.cancel()
        await coro


run(main)
```

### PR DESCRIPTION
**Pull request by dominik-schwabe**
Fixes #706.

### CODE REVIEW

**Comment by agronholm** [comment]
I'm reviewing this now. Would you mind adding a changelog entry?

**Comment by dominik-schwabe** [comment]
I updated the changelog, but I wasn't happy with it and changed it with a force push and I think this removed you commit https://github.com/agronholm/anyio/commit/6704b9ed0bfd2f651d04a8c7871073d268cfcfa2 .

**Comment by agronholm** [comment]
Yeah, just don't force push your changes :) I think my revisions made the entry more accurate, yes?

**Comment by dominik-schwabe** [comment]
Sorry for this, I didn't expect you to be so fast.

**Review by agronholm — APPROVED** [review]

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
