### PR TITLE
Fix cancel scope stack corruption when combining @asynccontextmanager and wrap_async_context_manager.

### PR DESCRIPTION
**Pull request by jonathanslenders**
See: https://github.com/agronholm/anyio/issues/381

### CODE REVIEW

**Comment by jonathanslenders** [comment]
@agronholm: No worries. Looking forward for this to be merged.

**Comment by agronholm** [comment]
I'm going to cut a bugfix release soon and I'll get this PR sorted out before that.

**Review by agronholm — APPROVED** [review]
Looks ready to me.

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
