### PR TITLE
Added TaskGroup.start_soon() and changed spawn() back into a coroutine function

### PR DESCRIPTION
**Pull request by agronholm**
One more step towards a trio-like API.

### CODE REVIEW

**Comment by agronholm** [comment]
This will break code written against the release candidates. The fix should be easy though.

**Comment by agronholm** [comment]
I'm only just wondering if we could emit deprecation warnings from the renamed methods. How would AnyIO 2/3 compatible code look like?

**Comment by smurfix** [comment]
Why doesn't `spawn` emit a DeprecationWarning?

**Comment by agronholm** [comment]
I'm trying to give library developers a way to use AnyIO 2.x and 3.x in the same code base without running into deprecation warnings. With free functions you could just conditionally import them but with methods it's not as simple. Can you suggest a solution?

**Comment by smurfix** [comment]
Hmm. Tricky, sounds like "defer adding a deprecation warning to `spawn` until anyio 3.1" is the best (or at least easiest-to-implement) idea here.

**Comment by agronholm** [comment]
I made them emit deprecation warnings after all, and pointed out that cross-compatible code could simply suppress the deprecation warnings. Good enough?

**Comment by smurfix** [comment]
Perfect.

**Review by smurfix — APPROVED** [review]

**Comment by agronholm** [comment]
Thanks for the review!

**Pull request merged**
