### PR TITLE
Fix cancellation propagation in inner task groups with spawn

### PR DESCRIPTION
**Pull request by ermakov-oleg**

### CODE REVIEW

**Comment by agronholm** [comment]
Good catch, thanks!

**Comment by ermakov-oleg** [comment]
@agronholm When do you plan to release a version containing this fix?

**Comment by agronholm** [comment]
I'm going to tackle #83 and #86 first, then I'll make a bugfix release. Some time this week.

**Comment by agronholm** [comment]
I've released v1.2.1 now.

**Comment by ermakov-oleg** [comment]
thanks!

**Pull request merged**
