### PR TITLE
Add start_new_session keyword argument to run_process() and open_process

### LINKED ISSUE #401: Sub-processes get SIGINT before cancellation when signal receiver is used
Maybe I'm doing something very silly here.  What I'm trying to do is catch SIGINT and schedule cancellation of tasks (some running sub-processes) later.

My example script below runs `bash -c "trap 'echo SIGINT CAUGHT' INT; sleep 100"` so that it will print `SIGINT CAUGHT` to stodut when it receives the signal and exits.  `open_process_callback_output()` is used to immediately print stdout from this process for debug sake.

```python
from contextlib import asynccontextmanager
import signal
import subprocess
import time

import anyio
from anyio.streams.text import TextReceiveStream

@asynccontextmanager
async def open_process_callback_output(cmd, on_stdout = None, on_stderr = None):
    """
    Open a process and if defined, call `on_stdout` for each line of stdout, and `on_stderr` for each line of stderr.
    """
    async def process_output(stream, func) -> None:
        async for text in TextReceiveStream(stream):
            for line in text.splitlines():
                func(line)

    proc = await anyio.open_process(cmd, stdout=PIPE, stderr=PIPE)
    async with anyio.create_task_group() as task_group:
        if on_stdout is not None:
            task_group.start_soon(process_output, proc.stdout, on_stdout)
        if on_stderr is not None:
            task_group.start_soon(process_output, proc.stderr, on_stderr)

        yield proc


async def task():
    async with open_process_callback_output('''bash -c "trap 'echo SIGINT CAUGHT' INT; sleep 100"''', on_stdout=lambda text: print(time.time(), f"\tstdout: {text}")) as proc:
        try:
            print(time.time(), "\ttask: waiting")
            await proc.wait()
        except anyio.get_cancelled_exc_class():
            print(time.time(), "\ttask: cancelled")
            raise
        finally:
            print(time.time(), "\ttask: done")


async def main():
    async def signal_handler():
        with anyio.open_signal_receiver(signal.SIGINT) as signals:
            async for signum in signals:
                print(time.time(), "\tsignal_handler: Got signal, cancel in 1 sec")
                await anyio.sleep(1)
                print(time.time(), "\tsignal_handler: cancelling")
                task_group.cancel_scope.cancel()

    async with anyio.create_task_group() as task_group:
        task_group.start_soon(task)
        task_group.start_soon(signal_handler)

print("asyncio")
anyio.run(main, backend='asyncio')
print("\ntrio")
anyio.run(main, backend='trio')
```

When I run this script and press CTRL-C after `task: waiting` is printed, I get:
```
asyncio
1639779714.8087683      task: waiting
^C1639779716.5815845    signal_handler: Got signal, cancel in 1 sec
1639779716.5836995      stdout: SIGINT CAUGHT
1639779716.5879638      task: done
1639779717.584897       signal_handler: cancelling

trio
1639779717.951388       task: waiting
^C1639779718.873392     stdout: SIGINT CAUGHT
1639779718.8739002      signal_handler: Got signal, cancel in 1 sec
1639779718.8772044      task: done
1639779719.8766265      signal_handler: cancelling
```

This shows that for both asyncio and trio, the process receives a signal before the `signal_handler` task and thus the bash script exits.  Soon after, the `task` coroutine exits (via `finally:`) without going through cancellation.

What I'd expect to happen is that SIGINT/CTRL-C would be caught by the signal handler and not immediately passed to the process.  Then, a second later the task would be cancelled, the process terminated, and so on.  For example:

```
asyncio
1639779714.8087683      task: waiting
^C1639779716.5815845    signal_handler: Got signal, cancel in 1 sec
1639779717.584897       signal_handler: cancelling
1639779717.5856995      stdout: SIGINT CAUGHT
1639779716.5879638      task: cancelled
1639779716.5879638      task: done

trio
1639779714.8087683      task: waiting
^C1639779716.5815845    signal_handler: Got signal, cancel in 1 sec
1639779717.584897       signal_handler: cancelling
1639779717.5856995      stdout: SIGINT CAUGHT
1639779716.5879638      task: cancelled
1639779716.5879638      task: done
```

### PR DESCRIPTION
**Pull request by uSpike**
Fixes #401

### CODE REVIEW

**Comment by uSpike** [comment]
Looks like mypy released 0.920 and broke a number of things

**Comment by agronholm** [comment]
> Looks like mypy released 0.920 and broke a number of things

Yup, I'm aware and am looking into fixing these issues.

**Comment by uSpike** [comment]
OK, I'll remove my changes to fix those errors.

**Comment by agronholm** [comment]
The new test fails on Windows due to lack of `os.setsid()`. You need to skip the test on Windows.

**Comment by uSpike** [comment]
Whoops, fixed.

**Review by agronholm — APPROVED** [review]

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
