### PR TITLE
Fixed AssertionError when using nest_asyncio

### LINKED ISSUE #840: Assertion error when `current_task()` returns an instance of `_asyncio.Task`
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.7.0

### Python version

3.12.8

### What happened?

It seems that sometimes when `asyncio.current_task()` is called in

https://github.com/agronholm/anyio/blob/97f064295b65dc1d7a2ded6fd24ba5be46d4c4f4/src/anyio/_backends/_asyncio.py#L2367

an instance of `_asyncio.Task` is returned. This then causes an assertion to be raised in

https://github.com/agronholm/anyio/blob/97f064295b65dc1d7a2ded6fd24ba5be46d4c4f4/src/anyio/_backends/_asyncio.py#L685-L694

### How can we reproduce the bug?

This is triggered in our test suite (fastapi, httpx, pytest-asyncio) after upgrading to anyio 4.7.0, but I haven't been able to come up with a MRE so hopefully this is enough to point maintainers to the potential fix.

### PR DESCRIPTION
**Pull request by agronholm**
## Changes

Refactored `TaskStateStore` to not check explicitly against `asyncio.Task`, as `nest-asyncio` replaces the asyncio modules.

Fixes #840. 

## Checklist

If this is a user-facing code change, like a bugfix or a new feature, please ensure that
you've fulfilled the following conditions (where applicable):

- [x] You've added tests (in `tests/`) added which would fail without your patch
- [ ] You've updated the documentation (in `docs/`, in case of behavior changes or new
features)
- [X] You've added a new changelog entry (in `docs/versionhistory.rst`).

If this is a trivial change, like a typo fix or a code reformatting, then you can ignore
these instructions.

### Updating the changelog

If there are no entries after the last release, use `**UNRELEASED**` as the version.
If, say, your patch fixes issue <span>#</span>123, the entry should look like this:

```
- Fix big bad boo-boo in task groups
  (`#123 <https://github.com/agronholm/anyio/issues/123>`_; PR by @yourgithubaccount)
```

If there's no issue linked, just link to your pull request instead by updating the
changelog after you've created the PR.

### CODE REVIEW

**Comment by agronholm** [comment]
I don't know how to write a test for this, as `nest_asyncio.apply()` is too invasive to be used in the test suite.

**Comment by graingert** [comment]
you could try with:

```
with mock.patch("asyncio.Task", asyncio.tasks._PyTask):
    ...
```

**Comment by agronholm** [comment]
I've added a test and verified that it fails without this patch.

**Comment by edgarrmondragon** [comment]
I can confirm that this patch fixes the problem for us

**Comment by sigridjineth** [comment]
@agronholm I just have came across this, but would be better implementing the logic for accomodating some varities of task-like objects I think. what's your opinion?

**Comment by agronholm** [comment]
> @agronholm I just have came across this, but would be better implementing the logic for accomodating some varities of task-like objects I think. what's your opinion?

If you find a problem not fixed by this PR, let me know. Otherwise I'm not inclined to add any more code just because.

**Review by graingert — APPROVED** [review]

**Comment by sandangel** [comment]
Hi, thank you so much for providing the fix for this issue. I wonder if we can create a release for this so I can download?

**Comment by sandangel** [comment]
Please take your time. I pin to 4.6.2 at the moment.

**Comment by agronholm** [comment]
> Please take your time. I pin to 4.6.2 at the moment.

All done now; v4.8.0 is out.

**Pull request merged**
