### PR TITLE
Add missing 'await'

### PR DESCRIPTION
**Pull request by makkus**
Maybe I'm missing something obvious, but it seems to me the spawn should be awaited, no?

### CODE REVIEW

**Comment by smurfix** [comment]
That's the master branch, so: no.

**Comment by makkus** [comment]
Sorry, just realized this has changed in latest version. Apologies, readthedocs uses 'latest', which is why I was confused.

**Comment by agronholm** [comment]
I'm confused. The docs on RTD default to "stable" which currently points to the v2.1.0 docs.

**Comment by makkus** [comment]
Yes, that's correct. I arrived via a search engine, and that's probably why I somehow ended up on 'latest'. I know I didn't manually set the version, so I assume it was just some fluke that probably doesn't affect (m)any others (and nothing you could do about it anyway). Sorry again for the confusion.

**Pull request closed without merging**
