### PR TITLE
Fixed feed_data after feed_eof assertion errors on asyncio

### LINKED ISSUE #490: Closing a process's stdout when there's more data to be read results in internal asyncio error
When using anyio with asyncio (This works fine with trio), if a subprocess is started with piped stdout and the stdout is closed (either explicitly or via context manager) before all data is read, asyncio will crash with a horrible traceback.

MVCE:

```python
import sys
import anyio

CODE = """\
import sys
for _ in range(1000):
    sys.stdout.buffer.write(bytes(range(256)))
"""

async def amain():
    async with await anyio.open_process([sys.executable, "-c", CODE]) as p:
        print(repr(await p.stdout.receive()))
        await p.stdout.aclose()  # The error even happens if you comment out this line!

if __name__ == "__main__":
    anyio.run(amain)
```

<details>
<summary>Output (after skipping the <code>print</code>'s output)</summary>

```
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
```

</details>

This behavior has been observed in the following environments:

* macOS 11.6.8, Python 3.10.8, anyio 3.6.2
* Debian 11 (bullseye), Python 3.8.13, anyio 3.6.1

### PR DESCRIPTION
**Pull request by agronholm**
## Changes

This removes the call to `self._stream.feed_eof()`, as it should not be done when the protocol is still sending data (and we can't prevent it from doing so). Instead, we set an internal flag and raise `ClosedResourceError` if someone tries to read from the stream after it's closed.

Fixes #490. 

## Checklist

If this is a user-facing code change, like a bugfix or a new feature, please ensure that
you've fulfilled the following conditions (where applicable):

- [X] You've added tests (in `tests/`) added which would fail without your patch
- [ ] You've updated the documentation (in `docs/`, in case of behavior changes or new
features)
- [X] You've added a new changelog entry (in `docs/versionhistory.rst`).

If this is a trivial change, like a typo fix or a code reformatting, then you can ignore
these instructions.

### Updating the changelog

If there are no entries after the last release, use `**UNRELEASED**` as the version.
If, say, your patch fixes issue #123, the entry should look like this:

`* Fix big bad boo-boo in task groups (#123
<https://github.com/agronholm/anyio/issues/123>_; PR by @yourgithubaccount)`

If there's no issue linked, just link to your pull request instead by updating the
changelog after you've created the PR.

### CODE REVIEW

**Comment by dolamroth** [comment]
Test #1

process.py
```
import time
import random

while True:
    print(random.random(), flush=True)
    time.sleep(0.01)
```

test_subprocess.py
```
import sys
from pathlib import Path

import anyio
from anyio.streams.buffered import BufferedByteReceiveStream


async def main():
    _script_path = str(Path(__file__).parent / "process.py")
    async with await anyio.open_process([sys.executable, _script_path]) as process:
        stream = BufferedByteReceiveStream(process.stdout)
        while True:
            try:
                output = await stream.receive_until(b"\n", 6)
                print(output, flush=True)
            except (anyio.ClosedResourceError, anyio.BrokenResourceError, anyio.EndOfStream):
                break


if __name__ == "__main__":
    anyio.run(main)
```

WITHOUT fix -- starts producing these after some time
```
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\r\n0.85027...539023763\r\n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\r\n0.85027...539023763\r\n')>
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\asyncio\streams.py", line 500, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
           ^^^^^^^^^^^^^
AssertionError: feed_data after feed_eof
```

WITH fix
Outputs numbers without issues. Works on both Windows and Linux.

**Comment by dolamroth** [comment]
I think, the second test is not linked to the `feed_eof` issue. Rather, it may be due to a bit contrintuitive behavior of `Process.aclose`.

It turns out, that (in the case, if error pops in user's code and not in subprocess) you need to explicitly terminate or kill process before calling `Process.aclose`, because it calls `await Process.wait()` before `Process.terminate()`.

If we substitute `__aexit__` in the 2nd test with the following code, it works and raises IndexError as expected

```py
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        self._proc.terminate()
        await self._proc.aclose()
        return False
```

**Review by Zac-HD — APPROVED** [review]
Looks good!  

Shutdown logic is always tricky, at least until someone very carefully implments it as a context manager 😅

**Comment by agronholm** [comment]
@graingert correctly pointed out that if the stream is aclosed _while_ another task is reading from it, it will hang, as there is no signal to stop waiting on the read. I'm struggling to write a proper test for this though.

**Comment by agronholm** [comment]
I've pushed an alternate solution, and an accompanying test to cover the case pointed out by @graingert.

**Review by graingert — APPROVED** [review]

**Comment by graingert** [comment]
Grumbles about asyncio streams

**Pull request merged**
