### PR TITLE
Solid init of `anyio` and `anyio.abc`

### PR DESCRIPTION
**Pull request by T-256**

### CODE REVIEW

**Comment by agronholm** [comment]
Would you like to explain this? The `... as X` imports are so mypy recognizes them as re-exports.

**Comment by agronholm** [comment]
Did you run the test suite, or `pre-commit` locally?

**Comment by T-256** [comment]
sorry, didn't aware of pre commit hook.
No I didn't test locally, this try was for https://github.com/agronholm/anyio/issues/545
let me fix it

**Comment by agronholm** [comment]
If there's a problem, how do I reproduce it? And how does this PR fix it?

**Comment by T-256** [comment]
now is ok
> If there's a problem, how do I reproduce it? And how does this PR fix it?

discussed in https://github.com/agronholm/anyio/issues/545 and https://github.com/encode/httpcore/issues/663 and it seems anyio issue on lazy imports.

**Comment by agronholm** [comment]
Why have I never seen this myself? And how does this PR propose to fix it?

Can you write me a trivial script to reproduce the issue?

**Comment by T-256** [comment]
I can't repro currently, but I had this problem before by iterating over `locals()`. I thought this would help.
Maybe @ebw44 can help us here, bcz I also didn't able to repro via his httpx example.

Currently I'm going to close this PR until we found an example to reproduce it.

**Comment by smurfix** [comment]
Huh. Iterating `locals` will do that. You need to create the loop variable before starting the iterator.

**Comment by agronholm** [comment]
But that's why I make a copy of locals _before_ I start iterating.

**Comment by T-256** [comment]
@agronholm do you have new idea on why this error happened?
```
File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\anyio\__init__.py", line 165, in <module>
    for key, value in list(locals().items()):
                      ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
```

Maybe `list` didn't do the job to shallow copy. document suggest to use `dict.copy` or `copy.deepcopy`

**Comment by agronholm** [comment]
But that is what `list()` does – it makes a shallow copy, just like `dict.copy()`. A deep copy on the other hand is slow and problematic, so we don't want that.

Under what circumstances have you been able to reproduce the problem?

**Comment by agronholm** [comment]
Let me put this in another way – can you prove that `locals().copy()` would solve the problem you're seeing?

**Comment by T-256** [comment]
> But that is what `list()` does – it makes a shallow copy, just like `dict.copy()`.

so perhaps the error is from `items` method, that is maybe iterating over locals

> Under what circumstances have you been able to reproduce the problem?

As I said above I couldn't even repro it. But i think this is coming from multi-threading problem.

**Comment by T-256** [comment]
> Let me put this in another way – can you prove that `locals().copy()` would solve the problem you're seeing?

@ebw44 should test this.

**Comment by ebw44** [comment]
I have tried to reproduce the problem I had without success. Mainly because my code has changed and I cannot go back to the problematic commit because the infrastructure my code depends on has evolved and is not compatible with that commit anymore.
At the time the problem was happening it was not consistent and seemed to be only when running under vscode debugger. Back then I was unable to create a unit test that triggered the problem. Maybe #692 gives some clue of why I got that problem and a way to reproduce it.

**Pull request closed without merging**
