### PR TITLE
Add example and docs link to the README

### PR DESCRIPTION
**Pull request by lordmauve**
I believe it's good practice to include a docs link in the README for users who arrive at the GitHub page and want to understand how to proceed.

I also added an example as a quick expression of the value proposition. This has pushed the detailed features list down the page a little but I think that is acceptable; if users arrive with no idea about what AnyIO does need to understand the value proposition before diving into the full features list.

### CODE REVIEW

**Comment by agronholm** [comment]
There is a documentation link at the top, but I suppose there is no harm in adding more explicit link. But I'm not sure about the given example. It doesn't really demonstrate any added value over asyncio/trio. If such an example was to be added, I think it should come after the feature list.

**Comment by lordmauve** [comment]
Yes, it's hard to write a useful example that is brief enough to give a useful taste. The example I added was condensed from https://anyio.readthedocs.io/en/stable/basics.html

Shall I just delete the example?

**Comment by agronholm** [comment]
> Yes, it's hard to write a useful example that is brief enough for a README. The example I added was condensed from https://anyio.readthedocs.io/en/stable/basics.html
> 
> Shall I just delete the example?

Yeah, I can at least merge the rest.

**Review by agronholm — APPROVED** [review]

**Comment by agronholm** [comment]
Thanks.

**Pull request merged**
